### ISSUE TITLE
FEBio Studio 2.7 crashes on Mac when "Auto time stepper" is set to remove

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#104] opened 2024-09-24 00:56 UTC
Hello,
This is the same as Issue #75 but for FEBio Studio 2.7. Probably the issue was not solved.
We experience a sudden FEBio Studio crash every time we set "Auto time stepper" to _remove_ on Mac.
Cheers,
Luca

**Comment by gateshian** [comment] 2024-09-24 11:08
Hi Luca,
Thanks for bringing this to our attention.  I confirm that I can reproduce this crash with the latest development version of FEBio Studio 2.7, on my Mac.

However, when I try to run FEBio Studio after compiling it on my Mac, this crash doesn't occur.  So it may have something to do with the settings used during compilation.  I will bring it to @michaelrossherron 's attention since he compiles the Mac version shared with users.
Best,
Gerard

**Comment by modenaxe** [comment] 2024-09-25 11:42
Hi Gerard,
thank you for investigating this! Probably what you described is the reason why @SteveMaas1978 couldn't reproduce it on FEBio Studio 2.2 on #75 - hopefully it can be easily solved!
Best regards,
Luca

**Comment by michaelrossherron** [comment] 2024-09-25 20:23
Luca, 

Thank you for finding this bug for us! I was able to trace the issue back to the version of Qt that we were using on macOS. I've updated to a newer version of Qt and it seems to have fixed the problem. Unfortunately you'll have to wait until our next official release before we're able to ship out a fix for this, but if all goes well, that may be happening in the next few weeks. 

Please let me know if you run into any other problems. 

Michael Herron

**Closed by michaelrossherron** 2024-09-25 20:23 UTC

**Comment by modenaxe** [comment] 2024-09-27 03:45
Fantastic, thank you @michaelrossherron - no rush on the release!
