### ISSUE TITLE
FEBio Studio (v2.6.0) on Mac crashes when asked to merge objects

### ISSUE THREAD

**Issue by hisl6802** [febiosoftware/FEBioStudio#88] opened 2024-04-19 17:45 UTC
I am using version 2.6.0 on an M1 Pro chip. Previously, I have not had any issues building multiple slices stacked and then merging. As of version 2.6.0 I am not able to merge the latest build I have created.

**Comment by michaelrossherron** [comment] 2024-04-25 16:36
Could you give us more information about this issue? What exactly do you mean by "building multiple slices stacked"? Are these separate, conforming meshes that you're trying to merge? How are you building them? Also, do you get any sort of error message when trying to merge, or does FEBio Studio crash without warning. 

Thanks,

Michael Herron

**Comment by SteveMaas1978** [comment] 2024-06-24 17:30
We recently release 2.7. I can't find any issues with merging slice objects, so I assume the issue is fixed. Closing now, but if the issue persists, please reopen or start a new issue. 

Best,

Steve

**Closed by SteveMaas1978** 2024-06-24 17:30 UTC
