### ISSUE TITLE
Issue with graphic view

### ISSUE THREAD

**Issue by tlrQkd** [febiosoftware/FEBioStudio#36] opened 2021-03-12 14:40 UTC
The graphic view is a black screen when I open the files (also when I just open a "new model") 
![image](https://user-images.githubusercontent.com/80532121/110954877-ffdb1880-8316-11eb-819e-f4cd9ca97826.png)

**Comment by SteveMaas1978** [comment] 2021-07-02 20:05
This has been reported on occasion, but we have never been able to reproduce this on any of our machines. 
The most likely cause is a graphics card that does not support the correct OpenGL version. (It needs to support at least OpenGL 3). I'm closing the issue, but feel free to reopen it if you can provide any additional information that could help us determine the cause.

**Closed by SteveMaas1978** 2021-07-02 20:05 UTC
