### ISSUE TITLE
FEBio Studio crashes on Mac when "Auto time stepper" is set to remove

### ISSUE THREAD

**Issue by modenaxe** [febiosoftware/FEBioStudio#75] opened 2023-09-27 01:08 UTC
Hello,

FEBio Studio 2.2 crashes instantaneously on Mac when "Auto time stepper" is set to remove, e.g. because we want to personalise time steps and step size.

Best regards,

Luca

**Comment by SteveMaas1978** [comment] 2024-06-24 17:32
Hi Luca, 

Sorry for the belated reply, but I can't reproduce this. I'm assuming this issue has been fixed. Closing this now but let us know if this is still a problem.

Best,

Steve

**Closed by SteveMaas1978** 2024-06-24 17:32 UTC

**Comment by modenaxe** [comment] 2024-09-23 07:22
Hi @SteveMaas1978 we are still experiencing this crashes also in FEBio Studio 2.7 - I will upload a screen capture video as soon as possible, but in the meanwhile I would like to reopen the issue.
